os:
  - linux-ppc64le
  - linux
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "node"
  - "iojs"

matrix:
  exclude:
  - os: linux-ppc64le
    node_js: "0.10"
  - os: linux-ppc64le
    node_js: "0.12"
  - os: linux-ppc64le
    node_js: "iojs"
